# Generated by Django 2.2.8 on 2019-12-05 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('semantic_score', models.IntegerField()),
                ('syntactic_score', models.IntegerField()),
                ('fun_score', models.IntegerField()),
                ('genre_score', models.IntegerField()),
                ('model', models.CharField(choices=[('A', 'ModelA'), ('B', 'ModelB'), ('C', 'ModelC')], max_length=1)),
                ('genre', models.CharField(choices=[('sport', 'Sport'), ('biography', 'Biography'), ('romance', 'Romance'), ('action', 'Action'), ('adventure', 'Adventure'), ('drama', 'Drama'), ('sci-fi', 'Sci-fi'), ('family', 'Family'), ('fantasy', 'Fantasy'), ('musical', 'Musical'), ('crime', 'Crime'), ('thriller', 'Thriller'), ('short', 'Short'), ('western', 'Western'), ('documentary', 'Documentary'), ('horror', 'Horror'), ('animation', 'Animation'), ('film-noir', 'Film-noir'), ('music', 'Music'), ('war', 'War'), ('mystery', 'Mystery')], max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
